Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'app/frontend/**/*'
    - 'spec/*_helper.rb'
    - 'db/schema.rb'

Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AsciiComments:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
